# Uncomment this line to define a global platform for your project
platform :ios, '15.0'

# CocoaPods analytics sends usage stats. Uncomment the line below to disable analytics.
# disable_cocoapods_analytics!

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.expand_path(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      # Enforce iOS 15.0 for all pods to prevent compatibility issues
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
end
