export const CHIT_REPORT_SLUGS = [
  'chit-group-report',
  'chit-auction-report',
  'chit-subscription-due',
  'chit-group-ledger',
  'chit-subscriber-ledger',
  'chit-auction-register',
  'chit-bid-history',
  'chit-prized-subscriber-report',
  'chit-dividend-register',
  'chit-foreman-commission-report',
  'chit-default-report',
  'chit-payout-report',
  'chit-security-pending-report',
  'chit-agreement-pending-report',
  'chit-receipt-register',
  'vacant-chit-report',
] as const;
