#!/usr/bin/env bash
# Codespaces first-boot setup — installs deps, creates a dev .env, and
# prepares the MySQL schema + seed data so `npm run dev` works immediately.
set -euo pipefail

if [ ! -f .env ]; then
  AUTH_SECRET=$(openssl rand -hex 32)
  PII_KEY=$(openssl rand -hex 32)
  CRON_SECRET=$(openssl rand -hex 16)
  cat > .env <<EOF
# Generated by .devcontainer/post-create.sh — dev-only values.
DATABASE_URL="mysql://root:root@db:3306/loantrack_dev"
AUTH_SECRET="${AUTH_SECRET}"
PII_ENCRYPTION_KEY="${PII_KEY}"
CRON_SECRET="${CRON_SECRET}"
NEXT_PUBLIC_APP_URL="http://localhost:3000"
TRUST_PROXY=false
RAZORPAY_MOCK_CHECKOUT=true
EOF
  echo "Created dev .env"
fi

npm ci

# MySQL may still be starting — retry schema push until it's reachable.
echo "Waiting for MySQL and pushing schema..."
for i in $(seq 1 30); do
  if npm run db:push; then
    break
  fi
  echo "MySQL not ready yet (attempt $i/30), retrying in 3s..."
  sleep 3
done

npm run db:seed || echo "Seed failed or already seeded — continuing."

echo ""
echo "──────────────────────────────────────────────"
echo " Ready. Start the app with:  npm run dev"
echo " Then open the forwarded port 3000."
echo "──────────────────────────────────────────────"
