import { mkdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import type { KnownGapResult, RunSummary } from './harness';

export function writeKnownGapsReport(input: {
  runId: string;
  source: string;
  knownGaps: KnownGapResult[];
  summary?: RunSummary;
}) {
  const evidenceDir = path.join(process.cwd(), 'Testing', 'qa_evidence', input.runId);
  mkdirSync(evidenceDir, { recursive: true });

  const lines = [
    '# LoanTrack E2E Business Known Gaps',
    '',
    `RUN_ID: ${input.runId}`,
    `Generated: ${new Date().toISOString()}`,
    '',
    `Generated by: ${input.source}`,
    '',
    'Known gaps are executable expected-failure probes. They stay visible without breaking the green gate while current code still has the documented defect.',
    '',
    '## Automation Report Separation',
    '',
    `- Passing automated cases: ${input.summary?.passed ?? 'see test console summary'}`,
    `- Manual/provider/device-only cases: ${input.summary?.manualProviderDeviceOnly ?? 0}`,
    `- Known current-code gaps: ${input.knownGaps.length}`,
    '',
    '## Known Current-Code Gaps',
    '',
  ];

  if (input.knownGaps.length === 0) {
    lines.push('No known gaps were observed by this run.', '');
  }

  for (const gap of input.knownGaps) {
    lines.push(
      `### ${gap.id}: ${gap.name}`,
      '',
      `- Current behavior: ${gap.currentBehavior}`,
      `- Expected behavior: ${gap.expectedBehavior}`,
      `- Evidence source: ${gap.evidenceSource}`,
      `- Business impact: ${gap.businessImpact}`,
      `- Assertion after fix: ${gap.fixedAssertion}`,
      `- Observed expected failure: ${gap.observedFailure}`,
      '',
    );
  }

  writeFileSync(path.join(evidenceDir, 'known-gaps.md'), `${lines.join('\n')}\n`, 'utf8');
}
