import type { KnownGapDetails } from './harness';

export const knownGapCatalog = {
  separateLoanApprovalBeforeDisbursement: {
    id: 'MM-GAP-001',
    classification: 'P1',
    currentBehavior: 'Admin-created loans activate immediately and debit branch cash during POST /api/v1/loans.',
    expectedBehavior: 'A branch-cash loan that requires approval should be created pending_review, leave branch cash unchanged, and disburse only when approval is accepted.',
    evidenceSource: 'app/api/v1/loans/route.ts sets bypassLoanApproval=true for non-agents and calls disburseFromBranch during create.',
    businessImpact: 'Approval and disbursement are coupled, so a loan can move real cash before an independent approval checkpoint is tested or enforced.',
    fixedAssertion: 'Creating the approval-required branch-cash loan returns pending_review and branch cash remains unchanged until /api/v1/approvals/[id]/approve.',
  },
  handoverApprovalDoesNotSettleWallet: {
    id: 'MM-GAP-002',
    classification: 'P0',
    currentBehavior: 'Approving a cash_handover request marks DailyCollection as settled but does not debit agent wallet or credit branch cash.',
    expectedBehavior: 'Approving handover should atomically reduce agent wallet/cash and increase branch cash/account balance by the handover amount.',
    evidenceSource: 'app/api/v1/approvals/[id]/approve/route.ts cash_handover branch only updates DailyCollection.status/lockedAt; lib/wallet.collectFromAgent has settlement logic but is not called there.',
    businessImpact: 'A settled handover can leave cash balances unreconciled, overstating agent-held cash and understating branch cash.',
    fixedAssertion: 'After approval, agent cash decreases by the handover amount, branch cash increases by the same amount, and wallet transactions exist for both sides.',
  },
  duplicateCollectionReplayDoubleCounts: {
    id: 'MM-GAP-003',
    classification: 'P0',
    currentBehavior: 'Replaying the same loan-level collection idempotency key can allocate to the next open instalment and create a second receipt/payment/wallet credit.',
    expectedBehavior: 'A duplicate replay should return the original result or a duplicate response without changing principal, interest, wallet, receipt, ledger, or instalment allocation totals.',
    evidenceSource: 'lib/collectionWrite.ts distributeCollectionAcrossLoan derives per-instalment keys as baseKey:instalmentId, so a replay after instalment #1 is paid can generate baseKey:instalment #2.',
    businessImpact: 'Repeated mobile/API submissions can overstate collections, agent cash, receipts, payment ledger, and loan paid count.',
    fixedAssertion: 'After submitting the same loan-level collection twice, collectionEntry/payment/paymentAllocation/wallet counts and loan.totalCollected remain unchanged from the first submission.',
  },
  dashboardBusinessDayMismatch: {
    id: 'MM-GAP-004',
    classification: 'P1',
    currentBehavior: 'Collection dashboard can return no dailyCollection while /api/v1/reports/daily and DB totals show the same business-day collection.',
    expectedBehavior: 'Dashboard, collection report, handover lookup, and DailyCollection DB rollup should resolve the same business date and totals.',
    evidenceSource: 'app/api/v1/collection/dashboard/route.ts uses startOfBusinessToday(), while app/api/v1/reports/daily/route.ts and collection/handover use Date.setHours(0,0,0,0).',
    businessImpact: 'Agents/admins can see inconsistent cash totals for the same business day, weakening handover and reconciliation confidence.',
    fixedAssertion: 'Dashboard totalCollected, /api/v1/reports/daily totalCollected, handover total, and DailyCollection.totalCollected all equal the same RUN_ID collection amount.',
  },
  genericReportExportNeedsWebSessionHarness: {
    id: 'REP-GAP-001',
    classification: 'provider-only',
    currentBehavior: '/api/v1/reports/[slug] and /api/v1/reports/[slug]/export require NextAuth web session context, while the business E2E harness currently authenticates via mobile bearer tokens.',
    expectedBehavior: 'The business E2E harness should be able to create a real web-session context or the routes should expose a supported API-auth path for export validation.',
    evidenceSource: 'app/api/v1/reports/[slug]/route.ts and app/api/v1/reports/[slug]/export/route.ts call requireApiContext from lib/apiAuth.ts, which uses auth(), getCurrentTenantId(), getUserAppType(), and getActiveBranchId().',
    businessImpact: 'Generic report/export route downloads cannot be exercised end-to-end in this API-only harness, so Phase 4 validates builders/serializers and keeps route-download coverage visible as a gap.',
    fixedAssertion: 'A Phase 4 test can call the generic report/export route handlers directly and receive CSV, XLSX, and PDF download responses for RUN_ID data.',
  },
  passwordResetExpiryUsesStatelessOtp: {
    id: 'SEC-GAP-001',
    classification: 'P2',
    currentBehavior: 'Password reset uses stateless HMAC OTP buckets and does not expose a persisted token object that can be aged directly by the E2E harness.',
    expectedBehavior: 'A reset-token expiry test should be able to create or inspect a reset token and prove it expires after the configured TTL.',
    evidenceSource: 'app/api/v1/auth/reset-password/route.ts validates current and previous 10-minute HMAC buckets with generateOtp/isValidOtp local functions.',
    businessImpact: 'The API rejects invalid/expired-looking codes, but token lifecycle observability is limited for deterministic end-to-end expiry automation.',
    fixedAssertion: 'A generated reset token older than the TTL is rejected, a fresh token is accepted, and both outcomes are observable without relying on hidden local functions.',
  },
  fileRouteNeedsBearerFirstHarness: {
    id: 'SEC-GAP-002',
    classification: 'P1',
    currentBehavior: '/api/files/[...path] calls NextAuth auth() before checking the mobile bearer token, so direct route-handler tests fail outside a Next request scope.',
    expectedBehavior: 'The file route should either check bearer tokens before auth() or the E2E harness should provide a real NextAuth request scope.',
    evidenceSource: 'app/api/files/[...path]/route.ts calls auth() before reading Authorization: Bearer; NextAuth auth() calls headers().',
    businessImpact: 'The tenant file access policy exists, but route-level private-file download isolation cannot be exercised in the current API-only harness.',
    fixedAssertion: 'A bearer-authenticated tenant A file request returns 200 for tenant A, 403 for tenant B, and 401 with no token.',
  },
  duplicateWebhookReplayDoubleCounts: {
    id: 'PAY-GAP-001',
    classification: 'P0',
    currentBehavior: 'Duplicate signed payment webhook replay must be proven idempotent for collections, receipts, ledgers, payment allocations, instalments, wallet, branch cash, and report totals.',
    expectedBehavior: 'A duplicate Razorpay collection webhook returns a duplicate/no-op result without changing any money-bearing rows or report totals.',
    evidenceSource: 'app/api/webhooks/razorpay/collections/route.ts and lib/selfPay.ts reconcileSelfPayToken idempotency by webhook_events and selfpay token status.',
    businessImpact: 'Webhook retries can overstate borrower repayments and accounting totals if idempotency regresses.',
    fixedAssertion: 'Submitting the same signed webhook twice leaves collectionEntry, paymentAllocation, walletTransaction, accountEntry, instalment received amount, and report totals unchanged after the first replay.',
  },
  duplicateNachReplayDoubleCounts: {
    id: 'PAY-GAP-002',
    classification: 'P0',
    currentBehavior: 'Duplicate NACH success/failure replay must be proven idempotent for presentation status and collection allocation.',
    expectedBehavior: 'A repeated NACH webhook returns duplicate/no-op behavior and does not create a second collection, allocation, ledger, or receipt.',
    evidenceSource: 'app/api/webhooks/razorpay/nach/route.ts and lib/nach.ts handlePresentationSuccess/handlePresentationFailure.',
    businessImpact: 'NACH provider retries can double-credit EMI payments or bounce accounting if replay protection regresses.',
    fixedAssertion: 'Submitting the same signed NACH webhook twice leaves nachPresentation, collectionEntry, paymentAllocation, walletTransaction, accountEntry, instalment, and report totals unchanged after the first replay.',
  },
  duplicateOfflineCollectionReplay: {
    id: 'MOB-GAP-001',
    classification: 'P0',
    currentBehavior: 'Duplicate mobile/offline collection payloads must be accepted once only.',
    expectedBehavior: 'A repeated mobile collection idempotency key is rejected or returns the original result without creating additional money rows.',
    evidenceSource: 'app/api/v1/collection/entry/route.ts calls lib/collectionWrite.ts submitCollectionEntry with idempotencyKey.',
    businessImpact: 'Offline sync retry can overstate cash, wallet, instalment paid amounts, and reports.',
    fixedAssertion: 'Posting the same mobile collection payload twice leaves all money-bearing DB counts and totals unchanged after the first submission.',
  },
  penaltyCronDuplicatePenalty: {
    id: 'RISK-GAP-001',
    classification: 'P0',
    currentBehavior: 'Penalty cron must not create duplicate pending penalties for the same overdue loan when rerun.',
    expectedBehavior: 'The second authorized penalty cron run updates the existing penalty only when gross due increases and never creates a second active penalty for the same loan.',
    evidenceSource: 'app/api/cron/accrue-penalties/route.ts uses prisma.penalty.findFirst pending/partial before create.',
    businessImpact: 'Duplicate penalties inflate borrower dues and penalty income reports.',
    fixedAssertion: 'Two cron runs leave one active penalty row per overdue loan and net due equals the service calculation.',
  },
  npaCronDuplicateHistory: {
    id: 'RISK-GAP-002',
    classification: 'P0',
    currentBehavior: 'NPA cron must not create duplicate NPA history entries when classification does not change.',
    expectedBehavior: 'The second NPA cron run updates review/provisioning snapshots only and does not add duplicate history for an unchanged category.',
    evidenceSource: 'lib/npa/npaClassifier.ts creates npaHistory only when newCategory differs from previousCategory.',
    businessImpact: 'Duplicate NPA history weakens audit trails and provisioning evidence.',
    fixedAssertion: 'Two NPA cron runs leave one history transition per actual category change and one provisioning snapshot per loan/date.',
  },
  reminderCronDuplicateNotifications: {
    id: 'CRON-GAP-001',
    classification: 'P1',
    currentBehavior: 'Reminder cron should not create duplicate notifications for the same instalment/business event when rerun.',
    expectedBehavior: 'A rerun recognizes an already-notified due reminder and leaves notification logs unchanged.',
    evidenceSource: 'app/api/cron/send-reminders/route.ts loops due instalments and calls notify without a visible per-event dedupe key.',
    businessImpact: 'Borrowers can receive repeated reminders for the same EMI and operators lose trust in notification totals.',
    fixedAssertion: 'Two reminder cron runs create at most one notification log per tenant/event/entityId/business date.',
  },
  optionalModuleBackendMissing: {
    id: 'MOD-GAP-001',
    classification: 'optional',
    currentBehavior: 'Optional module behavior is only a P0 blocker when the module is enabled in the test fixture.',
    expectedBehavior: 'Disabled optional modules should either reject API access or be explicitly tracked as optional known gaps.',
    evidenceSource: 'app/api/v1/chits, app/api/v1/vehicles, and app/api/v1/loans/[id]/product-repossession route availability varies by module.',
    businessImpact: 'Optional module incompleteness should stay visible without blocking core lending release gates.',
    fixedAssertion: 'Enabled optional modules pass route/service tests; disabled modules reject access consistently.',
  },
  providerOnlyLiveRoute: {
    id: 'PROVIDER-GAP-001',
    classification: 'provider-only',
    currentBehavior: 'Some provider-facing routes require live external credentials or calls when no mock switch is configured.',
    expectedBehavior: 'The automation should test lower safe services or signed webhook handlers and mark live-provider-only route execution as a known gap.',
    evidenceSource: 'lib/nach.ts createMandate/presentPayment call Razorpay APIs when tenant gateway credentials are enabled.',
    businessImpact: 'CI cannot safely call real payment/bank/SMS/device providers, so live-provider routes need a sandbox harness before becoming normal tests.',
    fixedAssertion: 'A signed sandbox/mock provider harness exercises the full route without external side effects.',
  },
} satisfies Record<string, KnownGapDetails>;
