/**
 * Micro Lending — master test-case catalogue.
 *
 * Single source of truth for both the Playwright specs and the HTML tracker.
 * A spec claims a case by putting its id in the test title: `test('[ML-101] ...')`.
 * scripts/build-ml-report.mjs joins this catalogue with the Playwright JSON
 * result and renders test-report/microlending.html.
 *
 * `rules` cite ENGINEERING_REFERENCE.md ids so a failure points at the invariant
 * it breaks, not just at a red assertion.
 */

export type Automation = 'auto' | 'manual';
export type Priority = 'P0' | 'P1' | 'P2';

export type MlCase = {
  id: string;
  area: string;
  title: string;
  priority: Priority;
  automation: Automation;
  rules?: string[];
  pre?: string;
  steps: string[];
  expected: string[];
};

export const AREAS = [
  'Registration & Provisioning',
  'Authentication & Session',
  'Branch Management',
  'Staff & RBAC',
  'Routes',
  'Capital & Branch Wallet',
  'Agent Float',
  'Customers & Approval',
  'Loans & Approval',
  'Frequencies & Interest Models',
  'Collection & Repayment',
  'Penalties',
  'Branch Isolation',
  'Accounting',
  'GPS & Agent Location',
  'Dashboard & Reports',
  'NPA',
  'Security & Negative',
  'Notifications & Approvals',
  'Borrower Portal',
] as const;

export const CASES: MlCase[] = [
  // ─────────────────────────── A. Registration ───────────────────────────
  {
    id: 'ML-001', area: 'Registration & Provisioning', priority: 'P0', automation: 'auto',
    title: 'Register page renders the signup form',
    steps: ['Open /register as an anonymous visitor'],
    expected: ['Business name, owner name, phone, email and password fields are visible', 'No server error, page is not blank'],
  },
  {
    id: 'ML-002', area: 'Registration & Provisioning', priority: 'P1', automation: 'auto',
    title: 'Registration rejects a non-Indian mobile number',
    rules: ['validateIndianMobile'],
    steps: ['POST /api/register/email with ownerPhone "12345"'],
    expected: ['HTTP 400', 'success:false with a phone validation message', 'No tenant row created'],
  },
  {
    id: 'ML-003', area: 'Registration & Provisioning', priority: 'P1', automation: 'auto',
    title: 'Registration rejects a malformed email',
    steps: ['POST /api/register/email with ownerEmail "not-an-email"'],
    expected: ['HTTP 400 with an email validation message'],
  },
  {
    id: 'ML-004', area: 'Registration & Provisioning', priority: 'P1', automation: 'auto',
    title: 'Registration rejects missing required fields',
    steps: ['POST /api/register/email with no businessName'],
    expected: ['HTTP 400 "Missing required fields"'],
  },
  {
    id: 'ML-005', area: 'Registration & Provisioning', priority: 'P1', automation: 'auto',
    title: 'Registration rejects an unknown or unpriced plan',
    steps: ['POST /api/register/email with selectedPlan "starter" (absent from SubscriptionPlanCatalog)'],
    expected: ['HTTP 400 "Select an active paid SaaS plan"', 'No tenant, branch or user is created'],
  },
  {
    id: 'ML-006', area: 'Registration & Provisioning', priority: 'P0', automation: 'auto',
    title: 'Successful registration provisions the tenant',
    steps: ['POST /api/register/email with a valid paid plan and module microlending'],
    expected: ['HTTP 200 success:true, requiresVerification:true', 'Tenant row exists with a slug derived from business name + module', 'Tenant status is active'],
  },
  {
    id: 'ML-007', area: 'Registration & Provisioning', priority: 'P0', automation: 'auto',
    title: 'Registration creates the Head Office branch',
    steps: ['Read the branch rows for the new tenant'],
    expected: ['Exactly one branch, name "Head Office", code "HQ", status active', 'enabledModules contains microlending'],
  },
  {
    id: 'ML-008', area: 'Registration & Provisioning', priority: 'P0', automation: 'auto',
    title: 'Registration creates the owner as a pending superadmin',
    steps: ['Read the user row created by registration'],
    expected: ['role superadmin', 'status "pending" until email verification', 'appType microlending', 'branchId = HQ branch'],
  },
  {
    id: 'ML-009', area: 'Registration & Provisioning', priority: 'P0', automation: 'auto',
    title: 'Registration snapshots the subscription limits',
    steps: ['Read TenantSubscription for the new tenant'],
    expected: ['plan = the selected plan, status active', 'maxBranches / maxAgents / maxActiveLoans copied from the catalog', 'enabledModules JSON contains microlending'],
  },
  {
    id: 'ML-010', area: 'Registration & Provisioning', priority: 'P1', automation: 'auto',
    title: 'Registration seeds the tenant default AppSettings',
    steps: ['Read AppSetting rows for the new tenant'],
    expected: ['currency_symbol and timezone seeded', 'default_penalty_per_day 50, penalty_grace_period 0, penalty_max_cap 0', 'customer_code_prefix CUS and loan_code_prefix LN with zeroed counters'],
  },
  {
    id: 'ML-011', area: 'Registration & Provisioning', priority: 'P2', automation: 'auto',
    title: 'Registration writes an audit log row',
    rules: ['SEC-2'],
    steps: ['Read AuditLog for entityType "tenant" and the new tenant id'],
    expected: ['One create row referencing the owner user'],
  },
  {
    id: 'ML-012', area: 'Registration & Provisioning', priority: 'P1', automation: 'auto',
    title: 'Owner is linked to the branch as its superadmin',
    steps: ['Read branch.superadminId and the SuperadminBranch join'],
    expected: ['branch.superadminId equals the owner id', 'A SuperadminBranch row exists for (owner, HQ)'],
  },
  {
    id: 'ML-013', area: 'Registration & Provisioning', priority: 'P0', automation: 'auto',
    title: 'Duplicate phone / username / email is refused',
    rules: ['MONEY-7'],
    steps: ['Re-POST /api/register/email with the same phone as an existing owner'],
    expected: ['HTTP 409 with a conflict message', 'No second tenant is created'],
  },
  {
    id: 'ML-014', area: 'Registration & Provisioning', priority: 'P1', automation: 'auto',
    title: 'Two tenants registered back to back stay separate',
    rules: ['SCOPE-1'],
    steps: ['Register tenant A and tenant B', 'Compare tenantIds, slugs and branch rows'],
    expected: ['Distinct tenantIds and slugs', 'Each tenant owns exactly its own HQ branch'],
  },

  // ─────────────────────────── B. Auth ───────────────────────────
  {
    id: 'ML-020', area: 'Authentication & Session', priority: 'P0', automation: 'auto',
    title: 'Login is blocked before email verification',
    steps: ['Submit the login form with the freshly registered owner credentials'],
    expected: ['Login is refused', 'The browser stays on /login — no portal or dashboard redirect'],
  },
  {
    id: 'ML-021', area: 'Authentication & Session', priority: 'P0', automation: 'auto',
    title: 'Verification link activates the owner account',
    steps: ['GET /api/auth/verify-email?token=<signed token>'],
    expected: ['No 500; a success or redirect response', 'User status flips from pending to active'],
  },
  {
    id: 'ML-022', area: 'Authentication & Session', priority: 'P0', automation: 'auto',
    title: 'A tampered verification token is rejected',
    steps: ['GET /api/auth/verify-email with the HMAC signature mutated'],
    expected: ['Activation refused', 'The target user status is unchanged'],
  },
  {
    id: 'ML-023', area: 'Authentication & Session', priority: 'P0', automation: 'auto',
    title: 'Superadmin logs in with username and lands in the app',
    steps: ['Open /login', 'Enter username and password', 'Submit'],
    expected: ['Redirected off /login', 'Landing page renders — not blank, no server error'],
  },
  {
    id: 'ML-024', area: 'Authentication & Session', priority: 'P1', automation: 'auto',
    title: 'Login also accepts the phone number as the identifier',
    steps: ['Log in using the owner phone number instead of the username'],
    expected: ['The same successful session is issued'],
  },
  {
    id: 'ML-025', area: 'Authentication & Session', priority: 'P0', automation: 'auto',
    title: 'Wrong password is refused',
    steps: ['Submit the login form with a bad password'],
    expected: ['Stays on /login with an error', 'No session cookie is issued'],
  },
  {
    id: 'ML-026', area: 'Authentication & Session', priority: 'P0', automation: 'auto',
    title: 'A protected route redirects an anonymous visitor to /login',
    rules: ['REQ-1'],
    steps: ['Open /microlending/dashboard with no session'],
    expected: ['Redirected to /login carrying a callbackUrl'],
  },
  {
    id: 'ML-027', area: 'Authentication & Session', priority: 'P0', automation: 'auto',
    title: '/api/v1/* without a bearer token returns 401',
    rules: ['REQ-3', 'API-4'],
    steps: ['GET /api/v1/customers with no Authorization header'],
    expected: ['HTTP 401', 'Envelope shape { data: null, error }'],
  },
  {
    id: 'ML-028', area: 'Authentication & Session', priority: 'P1', automation: 'auto',
    title: 'A deactivated user cannot log in',
    steps: ['Set an agent status to inactive', 'Attempt login as that agent'],
    expected: ['Login refused, browser stays on /login'],
  },
  {
    id: 'ML-029', area: 'Authentication & Session', priority: 'P1', automation: 'manual',
    title: 'Login rate limit engages after repeated failures',
    rules: ['AUTH-5'],
    pre: 'LOGIN_MAX_ATTEMPTS is deliberately raised in the E2E env, so this is verified outside the suite',
    steps: ['Submit repeated bad passwords for one username against default limits'],
    expected: ['Further attempts are throttled with a rate-limit message'],
  },
  {
    id: 'ML-030', area: 'Authentication & Session', priority: 'P2', automation: 'auto',
    title: 'Forgot-password page renders',
    steps: ['Open /forgot-password'],
    expected: ['The reset request form renders without error'],
  },

  // ─────────────────────────── C. Branch ───────────────────────────
  {
    id: 'ML-040', area: 'Branch Management', priority: 'P0', automation: 'auto',
    title: 'Superadmin opens the branch admin page',
    steps: ['Log in as superadmin', 'Open /admin/branches'],
    expected: ['The page renders with HQ listed', 'No redirect to /portal'],
  },
  {
    id: 'ML-041', area: 'Branch Management', priority: 'P0', automation: 'auto',
    title: 'Superadmin creates a second branch (Erode)',
    steps: ['Fill name "Erode" and a branch code', 'Pick self as branch superadmin', 'Submit'],
    expected: ['Branch row created for the tenant with status active', 'The branch appears in the list'],
  },
  {
    id: 'ML-042', area: 'Branch Management', priority: 'P0', automation: 'auto',
    title: 'Superadmin creates a third branch (Salem)',
    steps: ['Create branch "Salem" with its own code'],
    expected: ['Three branches exist: HQ, Erode, Salem', 'Each carries its own id and code'],
  },
  {
    id: 'ML-043', area: 'Branch Management', priority: 'P1', automation: 'auto',
    title: 'Duplicate branch code within a tenant is refused',
    steps: ['Attempt to create a second branch reusing the Erode code'],
    expected: ['Creation refused with a duplicate/conflict error', 'Branch count is unchanged'],
  },
  {
    id: 'ML-044', area: 'Branch Management', priority: 'P1', automation: 'auto',
    title: 'Branch creation respects the subscription maxBranches limit',
    steps: ['Create branches up to maxBranches, then attempt one more'],
    expected: ['The over-limit attempt is refused with a plan-limit message'],
  },
  {
    id: 'ML-045', area: 'Branch Management', priority: 'P0', automation: 'auto',
    title: 'Each branch carries its own enabledModules',
    rules: ['MOD-1'],
    steps: ['Read enabledModules on each branch'],
    expected: ['Module lists are stored per branch, not shared tenant-wide'],
  },
  {
    id: 'ML-046', area: 'Branch Management', priority: 'P0', automation: 'auto',
    title: 'Branch switcher lists every branch the superadmin owns',
    steps: ['Open a module page as superadmin', 'Open the branch switcher'],
    expected: ['HQ, Erode and Salem are all offered', 'An "All Branches" option exists'],
  },
  {
    id: 'ML-047', area: 'Branch Management', priority: 'P0', automation: 'auto',
    title: 'Selecting a branch pins the active branch for later reads',
    rules: ['SCOPE-6', 'REQ-2'],
    steps: ['Select Erode in the switcher', 'Reload a module list page'],
    expected: ['Active branch resolves to Erode', 'Lists are filtered to Erode'],
  },
  {
    id: 'ML-048', area: 'Branch Management', priority: 'P0', automation: 'auto',
    title: '"All Branches" is a null scope, not a role exemption',
    rules: ['SCOPE-15'],
    steps: ['Select All Branches as superadmin', 'Open the customers and loans lists'],
    expected: ['Rows from every branch appear', 'Picking a single branch immediately narrows the same lists'],
  },
  {
    id: 'ML-049', area: 'Branch Management', priority: 'P1', automation: 'auto',
    title: 'Branch edits persist',
    steps: ['Edit a branch phone number and save', 'Reload'],
    expected: ['The edited value persists on the branch row'],
  },

  // ─────────────────────────── D. Staff & RBAC ───────────────────────────
  {
    id: 'ML-060', area: 'Staff & RBAC', priority: 'P0', automation: 'auto',
    title: 'Superadmin creates a branch admin for HQ',
    rules: ['SCOPE-13'],
    steps: ['Open Settings → Agents with HQ active', 'Create a user with role admin'],
    expected: ['User row created with role admin, status active', 'branchId equals HQ'],
  },
  {
    id: 'ML-061', area: 'Staff & RBAC', priority: 'P0', automation: 'auto',
    title: 'Superadmin creates agent A1 in HQ',
    rules: ['SCOPE-13'],
    steps: ['Create a user with role agent while HQ is the active branch'],
    expected: ['The agent row is stamped with the HQ branchId', 'appType microlending'],
  },
  {
    id: 'ML-062', area: 'Staff & RBAC', priority: 'P0', automation: 'auto',
    title: 'Superadmin creates agent A2 in Erode',
    rules: ['SCOPE-13'],
    steps: ['Switch the active branch to Erode', 'Create agent A2'],
    expected: ['A2 is stamped with the Erode branchId, not HQ'],
  },
  {
    id: 'ML-063', area: 'Staff & RBAC', priority: 'P1', automation: 'auto',
    title: 'Duplicate staff username is refused',
    steps: ['Create a second user with an existing username'],
    expected: ['Refused with a conflict message; no duplicate row'],
  },
  {
    id: 'ML-064', area: 'Staff & RBAC', priority: 'P0', automation: 'auto',
    title: 'Agent list is branch-scoped',
    rules: ['SCOPE-12'],
    steps: ['Read the agent list with HQ active, then with Erode active'],
    expected: ['HQ shows A1 and not A2', 'Erode shows A2 and not A1'],
  },
  {
    id: 'ML-065', area: 'Staff & RBAC', priority: 'P0', automation: 'auto',
    title: 'Agent is refused the settings page server-side',
    rules: ['ROLE-4', 'X-5'],
    steps: ['Log in as agent A1', 'Navigate directly to /microlending/settings'],
    expected: ['The settings UI never renders for an agent'],
  },
  {
    id: 'ML-066', area: 'Staff & RBAC', priority: 'P0', automation: 'auto',
    title: 'Agent is refused reports, analytics, penalties and accounting',
    rules: ['ROLE-4'],
    steps: ['As A1 request /reports, /analytics, /penalties and /accounting under the module'],
    expected: ['None of the four render their content for an agent'],
  },
  {
    id: 'ML-067', area: 'Staff & RBAC', priority: 'P1', automation: 'auto',
    title: 'Agent cannot reach the module/branch selector portal',
    steps: ['As A1 open /portal'],
    expected: ['The agent is redirected back to their own dashboard'],
  },
  {
    id: 'ML-068', area: 'Staff & RBAC', priority: 'P1', automation: 'auto',
    title: 'Agent permission flags do not gate non-agents',
    rules: ['ROLE-5'],
    steps: ['Leave bypassLoanApproval false on the admin user', 'Originate a loan as that admin'],
    expected: ['Admin origination is not blocked by the agent-only flag'],
  },
  {
    id: 'ML-069', area: 'Staff & RBAC', priority: 'P2', automation: 'auto',
    title: 'Agent count is capped by the subscription',
    steps: ['Create agents beyond maxAgents'],
    expected: ['The over-limit creation is refused with a plan-limit message'],
  },
  {
    id: 'ML-070', area: 'Staff & RBAC', priority: 'P1', automation: 'auto',
    title: 'A role change takes effect on the next request',
    steps: ['Change a user role in the database while they hold a session', 'Have them load a gated page'],
    expected: ['The new role is honoured immediately — role and branch are re-read per session read'],
  },

  // ─────────────────────────── E. Routes ───────────────────────────
  {
    id: 'ML-085', area: 'Routes', priority: 'P0', automation: 'auto',
    title: 'Create route R1 in HQ and assign agent A1',
    steps: ['Settings → Routes with HQ active', 'Create route R1 and assign A1'],
    expected: ['Route row created with the HQ branchId and appType microlending', 'A RouteAgent link exists with A1 primary'],
  },
  {
    id: 'ML-086', area: 'Routes', priority: 'P0', automation: 'auto',
    title: 'Create route R2 in Erode and assign agent A2',
    steps: ['Switch to Erode', 'Create route R2 and assign A2'],
    expected: ['R2 carries the Erode branchId'],
  },
  {
    id: 'ML-087', area: 'Routes', priority: 'P0', automation: 'auto',
    title: 'Route list is branch-scoped',
    rules: ['SCOPE-12'],
    steps: ['Read routes with HQ active, then with Erode active'],
    expected: ['HQ shows only R1; Erode shows only R2'],
  },
  {
    id: 'ML-088', area: 'Routes', priority: 'P1', automation: 'auto',
    title: 'Route picker on the customer form offers only in-branch routes',
    rules: ['SCOPE-16'],
    steps: ['Open Customers → New as an HQ user'],
    expected: ['Only HQ routes appear', 'Erode routes are absent'],
  },
  {
    id: 'ML-089', area: 'Routes', priority: 'P2', automation: 'auto',
    title: 'A second agent can share a route, with one primary',
    steps: ['Assign a second HQ agent to R1', 'Set the primary agent'],
    expected: ['Both agents are linked; exactly one isPrimary'],
  },

  // ─────────────────────────── F. Capital & branch wallet ───────────────────────────
  {
    id: 'ML-100', area: 'Capital & Branch Wallet', priority: 'P0', automation: 'auto',
    title: 'Wallet page renders the branch cash pools for an owner',
    steps: ['Open /microlending/wallet as superadmin'],
    expected: ['Branch pool rows render with balances and a top-up control'],
  },
  {
    id: 'ML-101', area: 'Capital & Branch Wallet', priority: 'P0', automation: 'auto',
    title: 'Inject capital into the HQ branch pool',
    rules: ['MONEY-18', 'DB-5'],
    steps: ['Enter an amount with a note against HQ', 'Click Top up'],
    expected: ['The HQ BranchCashAccount balance increases by exactly that amount', 'A WalletTransaction ledger row is written'],
  },
  {
    id: 'ML-102', area: 'Capital & Branch Wallet', priority: 'P0', automation: 'auto',
    title: 'Capital ledger row is stamped with its branch',
    rules: ['SCOPE-13'],
    steps: ['Read the WalletTransaction created by the injection'],
    expected: ['branchId is the HQ branch, never null'],
  },
  {
    id: 'ML-103', area: 'Capital & Branch Wallet', priority: 'P0', automation: 'auto',
    title: 'Capital injected into Erode does not touch HQ',
    rules: ['SCOPE-3'],
    steps: ['Inject capital into Erode', 'Re-read both pool balances'],
    expected: ['Erode holds only its own injection', 'HQ is unchanged — neither pool aggregates the other'],
  },
  {
    id: 'ML-104', area: 'Capital & Branch Wallet', priority: 'P0', automation: 'auto',
    title: 'Wallet page is branch-scoped, with no superadmin exemption',
    rules: ['SCOPE-15'],
    steps: ['Select Erode as the active branch', 'Reload the wallet page'],
    expected: ['Only the Erode pool and Erode agents are listed', 'HQ figures are absent'],
  },
  {
    id: 'ML-105', area: 'Capital & Branch Wallet', priority: 'P1', automation: 'auto',
    title: 'Zero or negative capital is refused',
    steps: ['Attempt a top-up of 0 and of a negative amount'],
    expected: ['Both refused; no ledger row and no balance change'],
  },
  {
    id: 'ML-106', area: 'Capital & Branch Wallet', priority: 'P0', automation: 'auto',
    title: 'Agent sees their own float view, never the branch pool view',
    steps: ['Open the wallet page as agent A1'],
    expected: ['The agent float screen renders', 'No branch pool top-up control is present'],
  },
  {
    id: 'ML-107', area: 'Capital & Branch Wallet', priority: 'P1', automation: 'auto',
    title: 'Top up is a single click with no double posting',
    rules: ['DB-9'],
    steps: ['Click Top up once and wait for the result'],
    expected: ['Exactly one WalletTransaction is created', 'The balance moves by the entered amount once'],
  },

  // ─────────────────────────── G. Agent float ───────────────────────────
  {
    id: 'ML-120', area: 'Agent Float', priority: 'P0', automation: 'auto',
    title: 'Release float from the HQ pool to agent A1',
    rules: ['MONEY-18'],
    steps: ['On the wallet page enter an amount against A1 and click Release'],
    expected: ['A1 AgentAccount balance rises by that amount', 'The HQ pool falls by the same amount'],
  },
  {
    id: 'ML-121', area: 'Agent Float', priority: 'P0', automation: 'auto',
    title: 'Float release conserves cash across the two accounts',
    rules: ['MONEY-16'],
    steps: ['Compare pool + agent balances before and after the release'],
    expected: ['The sum is unchanged — cash moved, it was not created'],
  },
  {
    id: 'ML-122', area: 'Agent Float', priority: 'P0', automation: 'auto',
    title: 'Releasing more than the pool holds is refused',
    rules: ['MONEY-16', 'X-14'],
    steps: ['Attempt to release more than the branch pool balance'],
    expected: ['InsufficientFloatError surfaced as a 409', 'No balance changes'],
  },
  {
    id: 'ML-123', area: 'Agent Float', priority: 'P0', automation: 'auto',
    title: 'Agent wallet shows only that agent’s float',
    steps: ['Log in as A1 and open the wallet'],
    expected: ['A1 balance and A1 ledger only', 'No other agent appears'],
  },
  {
    id: 'ML-124', area: 'Agent Float', priority: 'P0', automation: 'auto',
    title: 'Float released in HQ is invisible in the Erode wallet view',
    rules: ['SCOPE-3', 'SCOPE-13'],
    steps: ['Select Erode', 'Read the agent float table'],
    expected: ['A1 (HQ) does not appear', 'Erode totals exclude HQ float'],
  },
  {
    id: 'ML-125', area: 'Agent Float', priority: 'P1', automation: 'auto',
    title: 'Collect float back from an agent',
    steps: ['Click Collect against A1 and confirm'],
    expected: ['Agent balance falls and the branch pool rises by the same amount'],
  },
  {
    id: 'ML-126', area: 'Agent Float', priority: 'P1', automation: 'auto',
    title: 'Collecting more than the agent holds is refused',
    rules: ['MONEY-16'],
    steps: ['Attempt to collect more than the agent float'],
    expected: ['Refused with insufficient float; balances unchanged'],
  },
  {
    id: 'ML-127', area: 'Agent Float', priority: 'P2', automation: 'auto',
    title: 'Agent raises a cash handover and the admin confirms it',
    steps: ['As A1 request a handover', 'As admin collect that handover'],
    expected: ['Handover status moves pending → collected', 'Cash lands back in the branch pool'],
  },
  {
    id: 'ML-128', area: 'Agent Float', priority: 'P2', automation: 'auto',
    title: 'Admin can reject a handover',
    steps: ['Reject a pending handover'],
    expected: ['Status becomes rejected; no cash moves'],
  },
  {
    id: 'ML-129', area: 'Agent Float', priority: 'P0', automation: 'auto',
    title: 'Every wallet movement carries a branchId',
    rules: ['SCOPE-13'],
    steps: ['Read all WalletTransaction rows created by the run'],
    expected: ['No row has branchId null'],
  },
  {
    id: 'ML-130', area: 'Agent Float', priority: 'P1', automation: 'auto',
    title: 'Release is a single click with no double debit',
    steps: ['Click Release once'],
    expected: ['Exactly one release ledger row; the pool drops once'],
  },

  // ─────────────────────────── H. Customers ───────────────────────────
  {
    id: 'ML-150', area: 'Customers & Approval', priority: 'P0', automation: 'auto',
    title: 'Agent opens the new-customer form',
    steps: ['As A1 open /microlending/customers/new'],
    expected: ['Name, phone, address and route fields render', 'The route dropdown is populated'],
  },
  {
    id: 'ML-151', area: 'Customers & Approval', priority: 'P0', automation: 'auto',
    title: 'Agent-created customer lands in pending_review',
    steps: ['Submit a valid customer as A1 with bypassCustomerApproval false'],
    expected: ['Customer row status is pending_review', 'It is not yet usable for a loan'],
  },
  {
    id: 'ML-152', area: 'Customers & Approval', priority: 'P0', automation: 'auto',
    title: 'Customer is stamped with the branch of its route, not its author',
    rules: ['SCOPE-7'],
    steps: ['Read the created customer row'],
    expected: ['branchId equals the route’s branch', 'agentId is the route primary agent'],
  },
  {
    id: 'ML-153', area: 'Customers & Approval', priority: 'P0', automation: 'auto',
    title: 'Pending customer appears in the admin approvals queue',
    steps: ['Log in as the HQ admin and open /microlending/approvals'],
    expected: ['The pending customer is listed with approve and reject actions'],
  },
  {
    id: 'ML-154', area: 'Customers & Approval', priority: 'P0', automation: 'auto',
    title: 'Admin approval activates the customer',
    steps: ['Approve the pending customer'],
    expected: ['Customer status becomes active', 'It leaves the pending queue'],
  },
  {
    id: 'ML-155', area: 'Customers & Approval', priority: 'P1', automation: 'auto',
    title: 'Approve is a single click',
    steps: ['Click Approve exactly once and wait'],
    expected: ['The record is approved without a second confirmation click'],
  },
  {
    id: 'ML-156', area: 'Customers & Approval', priority: 'P1', automation: 'auto',
    title: 'Admin can reject a customer with notes',
    steps: ['Reject a second pending customer with review notes'],
    expected: ['Status becomes rejected and the notes are stored'],
  },
  {
    id: 'ML-157', area: 'Customers & Approval', priority: 'P1', automation: 'auto',
    title: 'Admin-created customer is active immediately',
    steps: ['Create a customer while logged in as admin'],
    expected: ['Status is active with no approval step'],
  },
  {
    id: 'ML-158', area: 'Customers & Approval', priority: 'P1', automation: 'auto',
    title: 'Customer codes follow the tenant prefix and never collide',
    steps: ['Create several customers and read their codes'],
    expected: ['Codes use the configured prefix', 'No duplicate code inside the tenant'],
  },
  {
    id: 'ML-159', area: 'Customers & Approval', priority: 'P1', automation: 'auto',
    title: 'Duplicate customer phone within a tenant is refused',
    steps: ['Create a customer with an already-used phone'],
    expected: ['Refused with a duplicate message; no second row'],
  },
  {
    id: 'ML-160', area: 'Customers & Approval', priority: 'P1', automation: 'auto',
    title: 'Aadhaar is encrypted at rest',
    rules: ['SEC-1', 'X-13'],
    steps: ['Create a customer with an Aadhaar number', 'Read the stored column'],
    expected: ['The stored value is not the plaintext number'],
  },
  {
    id: 'ML-161', area: 'Customers & Approval', priority: 'P0', automation: 'auto',
    title: 'Agent sees only their own customers',
    rules: ['SCOPE-5'],
    steps: ['As A1 open the customers list'],
    expected: ['Only customers on A1 routes are listed'],
  },
  {
    id: 'ML-162', area: 'Customers & Approval', priority: 'P0', automation: 'auto',
    title: 'Customer list is branch-scoped for staff',
    rules: ['SCOPE-3'],
    steps: ['Create a customer in Erode', 'View the customers list with HQ active'],
    expected: ['The Erode customer is absent from the HQ list and vice versa'],
  },
  {
    id: 'ML-163', area: 'Customers & Approval', priority: 'P1', automation: 'auto',
    title: 'Agent cannot edit a customer',
    rules: ['ROLE-4'],
    steps: ['As A1 request the customer edit route directly'],
    expected: ['Redirected away; no edit form and no write'],
  },
  {
    id: 'ML-164', area: 'Customers & Approval', priority: 'P0', automation: 'auto',
    title: 'A customer id from another tenant returns 404, not 403',
    rules: ['API-5', 'X-12'],
    steps: ['Call /api/v1/customers/<other tenant id> with a valid token'],
    expected: ['HTTP 404 — existence is not confirmed'],
  },

  // ─────────────────────────── I. Loans ───────────────────────────
  {
    id: 'ML-180', area: 'Loans & Approval', priority: 'P0', automation: 'auto',
    title: 'Agent opens the new-loan form with an approved customer',
    steps: ['As A1 open /microlending/loans/new'],
    expected: ['The customer picker offers the approved HQ customer', 'Principal, frequency, tenure and start date render'],
  },
  {
    id: 'ML-181', area: 'Loans & Approval', priority: 'P0', automation: 'auto',
    title: 'Agent-originated loan is pending_review and disburses nothing',
    rules: ['MONEY-8'],
    steps: ['Submit a daily loan as A1 with bypassLoanApproval false'],
    expected: ['Loan status is pending_review', 'No wallet movement and no cash-book entry yet'],
  },
  {
    id: 'ML-182', area: 'Loans & Approval', priority: 'P0', automation: 'auto',
    title: 'Pending loan notifies the approvers and joins their queue',
    rules: ['X-23', 'MONEY-8'],
    pre: 'A pending loan is queued by its own status; ApprovalRequest carries edit requests, not originations',
    steps: ['Originate as an agent without the bypass flag', 'Read the loan status and the approver notifications'],
    expected: [
      'The loan sits at pending_review, which is what the approvals page reads',
      'notifyApprovers() has queued at least one notification naming the contract',
    ],
  },
  {
    id: 'ML-183', area: 'Loans & Approval', priority: 'P0', automation: 'auto',
    title: 'Admin sees the pending loan in the approvals queue',
    steps: ['As the HQ admin open /microlending/approvals'],
    expected: ['The pending loan is listed with its principal and customer'],
  },
  {
    id: 'ML-184', area: 'Loans & Approval', priority: 'P0', automation: 'auto',
    title: 'Approving the loan activates it',
    rules: ['DB-5'],
    steps: ['Approve the pending loan'],
    expected: ['Loan status becomes active', 'The schedule is live'],
  },
  {
    id: 'ML-185', area: 'Loans & Approval', priority: 'P1', automation: 'auto',
    title: 'Loan approval is a single click',
    steps: ['Click Approve once'],
    expected: ['One approval, one disbursal, no duplicate postings'],
  },
  {
    id: 'ML-186', area: 'Loans & Approval', priority: 'P0', automation: 'auto',
    title: 'Rejecting a loan moves no money',
    steps: ['Originate a second pending loan and reject it'],
    expected: ['Status is rejected', 'Branch pool, agent float and cash book are unchanged'],
  },
  {
    id: 'ML-187', area: 'Loans & Approval', priority: 'P0', automation: 'auto',
    title: 'Contract numbers use the frequency prefix',
    rules: ['ORIG-1'],
    steps: ['Originate one loan of each frequency and read the loanCodes'],
    expected: ['Daily DL, weekly WL, bi-weekly BWL and monthly ML prefixes'],
  },
  {
    id: 'ML-188', area: 'Loans & Approval', priority: 'P0', automation: 'auto',
    title: 'Contract numbers are unique tenant-wide',
    rules: ['ORIG-1', 'ORIG-2'],
    steps: ['Originate several loans across branches', 'Group the loanCodes'],
    expected: ['No duplicate loanCode inside the tenant'],
  },
  {
    id: 'ML-189', area: 'Loans & Approval', priority: 'P0', automation: 'auto',
    title: 'Loan is stamped with the customer’s branch',
    rules: ['SCOPE-7'],
    steps: ['Originate a loan for an HQ customer while another branch is active'],
    expected: ['loan.branchId is the customer’s branch, not the filer’s'],
  },
  {
    id: 'ML-190', area: 'Loans & Approval', priority: 'P0', automation: 'auto',
    title: 'Cash disbursal from agent float debits that float',
    rules: ['MONEY-17'],
    steps: ['Disburse a cash loan against A1 float'],
    expected: ['A1 float drops by the disbursed amount', 'A WalletTransaction records the debit'],
  },
  {
    id: 'ML-191', area: 'Loans & Approval', priority: 'P0', automation: 'auto',
    title: 'Disbursal beyond available float is refused atomically',
    rules: ['MONEY-16', 'DB-5', 'X-14'],
    steps: ['Attempt a cash disbursal larger than the available float'],
    expected: ['HTTP 409', 'No loan row is committed — the whole transaction rolls back'],
  },
  {
    id: 'ML-192', area: 'Loans & Approval', priority: 'P0', automation: 'auto',
    title: 'Staff origination funds from the branch pool, not an agent float',
    rules: ['MONEY-17', 'MONEY-18'],
    steps: ['Originate an active loan as admin', 'Compare the branch pool and every agent float'],
    expected: ['The branch pool falls by the disbursed amount', 'No agent float is touched'],
  },
  {
    id: 'ML-193', area: 'Loans & Approval', priority: 'P0', automation: 'auto',
    title: 'Origination writes the cash book',
    rules: ['ACC-6'],
    steps: ['Read AccountEntry rows for the disbursed loan'],
    expected: ['A cash-book entry exists per payout leg'],
  },
  {
    id: 'ML-194', area: 'Loans & Approval', priority: 'P1', automation: 'auto',
    title: 'Origination writes an audit row',
    rules: ['SEC-2', 'DB-5'],
    steps: ['Read AuditLog for entityType loan'],
    expected: ['A create row exists for every originated loan'],
  },
  {
    id: 'ML-195', area: 'Loans & Approval', priority: 'P0', automation: 'auto',
    title: 'Instalment schedule is generated with the right row count',
    rules: ['MONEY-1'],
    steps: ['Read the instalments of each originated loan'],
    expected: ['Row count equals the tenure', 'Instalment numbers run 1..n with no gaps'],
  },
  {
    id: 'ML-196', area: 'Loans & Approval', priority: 'P1', automation: 'auto',
    title: 'Schedule cannot be edited once money has moved',
    rules: ['MONEY-12'],
    steps: ['Collect one instalment, then attempt to change the schedule'],
    expected: ['The edit is refused'],
  },
  {
    id: 'ML-197', area: 'Loans & Approval', priority: 'P1', automation: 'auto',
    title: 'Invalid principal or tenure is rejected',
    steps: ['Attempt origination with principal 0 and with tenure 0'],
    expected: ['HTTP 400 both times; no loan row'],
  },
  {
    id: 'ML-198', area: 'Loans & Approval', priority: 'P1', automation: 'auto',
    title: 'Admin origination bypasses approval',
    rules: ['MONEY-8'],
    steps: ['Originate a loan as the branch admin'],
    expected: ['The loan is active immediately'],
  },

  // ─────────────────────────── J. Frequencies & interest ───────────────────────────
  {
    id: 'ML-215', area: 'Frequencies & Interest Models', priority: 'P0', automation: 'auto',
    title: 'Daily loan with an upfront fixed deduction',
    rules: ['MONEY-1'],
    steps: ['Originate principal 30000, upfront_fixed deduction 3000, tenure 30, frequency daily'],
    expected: ['totalPayable equals the principal', 'disbursed equals principal − deduction', '30 instalments spaced one day apart'],
  },
  {
    id: 'ML-216', area: 'Frequencies & Interest Models', priority: 'P0', automation: 'auto',
    title: 'Daily loan with an upfront percentage deduction',
    steps: ['Originate principal 20000, upfront_percentage 10, tenure 20, daily'],
    expected: ['Deduction is 10% of principal', 'totalPayable still equals the principal'],
  },
  {
    id: 'ML-217', area: 'Frequencies & Interest Models', priority: 'P0', automation: 'auto',
    title: 'Weekly schedule steps by seven days',
    steps: ['Originate a weekly loan with tenure 10'],
    expected: ['10 instalments', 'Consecutive due dates differ by exactly 7 days'],
  },
  {
    id: 'ML-218', area: 'Frequencies & Interest Models', priority: 'P0', automation: 'auto',
    title: 'Bi-weekly schedule steps by fourteen days',
    steps: ['Originate a bi-weekly loan with tenure 6'],
    expected: ['6 instalments', 'Consecutive due dates differ by exactly 14 days'],
  },
  {
    id: 'ML-219', area: 'Frequencies & Interest Models', priority: 'P0', automation: 'auto',
    title: 'Monthly schedule honours the chosen due day',
    steps: ['Originate a monthly loan with a due day and tenure 12'],
    expected: ['12 instalments', 'Each falls on the chosen day of successive months'],
  },
  {
    id: 'ML-220', area: 'Frequencies & Interest Models', priority: 'P0', automation: 'auto',
    title: 'EMI flat interest adds interest on top of the principal',
    rules: ['MONEY-1'],
    steps: ['Originate emi_flat, principal 100000, rate 12, monthly, tenure 12'],
    expected: ['totalPayable equals principal + principal × rate%', 'Instalments sum to totalPayable'],
  },
  {
    id: 'ML-221', area: 'Frequencies & Interest Models', priority: 'P1', automation: 'auto',
    title: 'EMI floating uses a reducing-balance schedule',
    steps: ['Originate emi_floating, principal 100000, rate 18, monthly, tenure 12'],
    expected: ['The schedule follows the reducing-balance EMI, not a flat split'],
  },
  {
    id: 'ML-222', area: 'Frequencies & Interest Models', priority: 'P0', automation: 'auto',
    title: 'Interest-only is refused when the tenant flag is off',
    rules: ['MONEY-2'],
    steps: ['With interest_only_enabled unset, POST an interest_only origination'],
    expected: ['Refused server-side, not merely hidden in the UI'],
  },
  {
    id: 'ML-223', area: 'Frequencies & Interest Models', priority: 'P0', automation: 'auto',
    title: 'Interest-only bills interest monthly with a bullet principal',
    rules: ['MONEY-3', 'MONEY-5'],
    pre: 'AppSetting interest_only_enabled = true',
    steps: ['Originate interest_only, principal 100000, 2% per month, monthly, tenure 6'],
    expected: ['Each instalment is the monthly interest', 'interestRate and outstandingPrincipal persist on the loan'],
  },
  {
    id: 'ML-224', area: 'Frequencies & Interest Models', priority: 'P0', automation: 'auto',
    title: 'Interest-only with a non-monthly frequency is rejected',
    rules: ['MONEY-3'],
    steps: ['POST an interest_only origination with frequency daily'],
    expected: ['HTTP 400 — a monthly rate is never billed daily'],
  },
  {
    id: 'ML-225', area: 'Frequencies & Interest Models', priority: 'P1', automation: 'auto',
    title: 'Rounding remainder lands on the final instalment',
    rules: ['DB-13'],
    steps: ['Originate an amount that does not divide evenly by the tenure'],
    expected: ['Σ instalments equals totalPayable exactly', 'Only the last instalment differs'],
  },
  {
    id: 'ML-226', area: 'Frequencies & Interest Models', priority: 'P1', automation: 'auto',
    title: 'Loan end date equals the last instalment due date',
    steps: ['Compare loan.endDate with max(instalment.dueDate) for every loan'],
    expected: ['They match for every frequency'],
  },
  {
    id: 'ML-227', area: 'Frequencies & Interest Models', priority: 'P1', automation: 'auto',
    title: 'Persisted loan totals match the calculator preview',
    rules: ['MONEY-1', 'API-8'],
    steps: ['Recompute each loan with calculateLoanPreview and compare with the stored row'],
    expected: ['perInstalment, totalPayable and disbursed agree'],
  },

  // ─────────────────────────── K. Collection ───────────────────────────
  {
    id: 'ML-250', area: 'Collection & Repayment', priority: 'P0', automation: 'auto',
    title: 'Agent collection sheet lists dues for their routes',
    steps: ['As A1 open /microlending/collection'],
    expected: ['The active loan’s due instalment is listed with its amount'],
  },
  {
    id: 'ML-251', area: 'Collection & Repayment', priority: 'P0', automation: 'auto',
    title: 'Full collection marks the instalment paid',
    rules: ['MONEY-11'],
    steps: ['Submit the exact due amount in cash'],
    expected: ['Instalment status becomes paid', 'receivedAmount equals dueAmount'],
  },
  {
    id: 'ML-252', area: 'Collection & Repayment', priority: 'P0', automation: 'auto',
    title: 'Partial collection marks the instalment partial',
    rules: ['MONEY-11'],
    steps: ['Submit less than the due amount'],
    expected: ['Status becomes partial with the received amount recorded'],
  },
  {
    id: 'ML-253', area: 'Collection & Repayment', priority: 'P0', automation: 'auto',
    title: 'Allocation fills today first, then oldest overdue, then future',
    rules: ['MONEY-10'],
    steps: ['Build a loan with a backlog', 'Pay an amount covering more than one instalment'],
    expected: ['Today’s due clears first', 'Then the oldest overdue, then the soonest future'],
  },
  {
    id: 'ML-254', area: 'Collection & Repayment', priority: 'P0', automation: 'auto',
    title: 'A retried collection does not double-post',
    rules: ['MONEY-13', 'DB-9'],
    steps: ['Submit the same collection twice with identical parameters'],
    expected: ['Only one collection entry and one instalment movement'],
  },
  {
    id: 'ML-255', area: 'Collection & Repayment', priority: 'P0', automation: 'auto',
    title: 'Cash collection increases the collecting agent’s float',
    rules: ['MONEY-17'],
    steps: ['Collect in cash and re-read the agent float'],
    expected: ['Agent float rises by the collected amount'],
  },
  {
    id: 'ML-256', area: 'Collection & Repayment', priority: 'P1', automation: 'auto',
    title: 'A receipt record is produced for a collection',
    steps: ['Read the receipt for the collection entry'],
    expected: ['A receipt exists with the amount and customer'],
  },
  {
    id: 'ML-257', area: 'Collection & Repayment', priority: 'P1', automation: 'auto',
    title: 'Loan closes when the last instalment is settled',
    rules: ['MONEY-11'],
    steps: ['Pay every remaining instalment of a short loan'],
    expected: ['Loan status resolves to closed', 'No instalment remains unpaid'],
  },
  {
    id: 'ML-258', area: 'Collection & Repayment', priority: 'P0', automation: 'auto',
    title: 'Collection rows are branch-scoped',
    rules: ['SCOPE-3'],
    steps: ['Collect in HQ and in Erode', 'Read the collection page under each branch'],
    expected: ['Each branch shows only its own entries and totals'],
  },
  {
    id: 'ML-259', area: 'Collection & Repayment', priority: 'P2', automation: 'auto',
    title: 'Non-cash collection does not move physical float',
    rules: ['MONEY-17'],
    steps: ['Record a UPI collection'],
    expected: ['The cash book records it; agent float is unchanged'],
  },

  // ─────────────────────────── L. Penalties ───────────────────────────
  {
    id: 'ML-280', area: 'Penalties', priority: 'P0', automation: 'auto',
    title: 'An unpaid instalment past its due date is missed',
    rules: ['MONEY-11'],
    steps: ['Back-date a loan so an instalment is overdue', 'Re-read the instalment status'],
    expected: ['Status resolves to missed, not upcoming'],
  },
  {
    id: 'ML-281', area: 'Penalties', priority: 'P0', automation: 'auto',
    title: 'Penalty accrual follows days × rate beyond the grace period',
    rules: ['MONEY-14'],
    steps: ['Set penalty per day and grace, then accrue'],
    expected: ['Accrued equals Σ max(0, daysOverdue − grace) × penaltyPerDay'],
  },
  {
    id: 'ML-282', area: 'Penalties', priority: 'P1', automation: 'auto',
    title: 'Penalty is capped by the tenant maximum',
    rules: ['MONEY-14'],
    steps: ['Set penalty_max_cap and accrue past it'],
    expected: ['The accrued penalty stops at the cap'],
  },
  {
    id: 'ML-283', area: 'Penalties', priority: 'P0', automation: 'auto',
    title: 'Gross penalty only ever increases; reductions are waivers',
    rules: ['MONEY-15'],
    steps: ['Accrue, then reduce the penalty'],
    expected: ['Gross is never rewritten downwards', 'The reduction is recorded as a waiver'],
  },
  {
    id: 'ML-284', area: 'Penalties', priority: 'P1', automation: 'auto',
    title: 'Penalty accrual is idempotent across re-runs',
    rules: ['CRON-2'],
    steps: ['Run the accrual twice for the same day'],
    expected: ['No duplicate penalty rows and no doubled amount'],
  },
  {
    id: 'ML-285', area: 'Penalties', priority: 'P1', automation: 'auto',
    title: 'Penalties page is branch-scoped and closed to agents',
    rules: ['SCOPE-3', 'ROLE-4'],
    steps: ['Open the penalties page as admin under each branch, then as an agent'],
    expected: ['Only the active branch’s penalties are listed', 'The agent is refused'],
  },

  // ─────────────────────────── M. Branch isolation ───────────────────────────
  {
    id: 'ML-300', area: 'Branch Isolation', priority: 'P0', automation: 'auto',
    title: 'Dashboard KPIs are computed per branch',
    rules: ['SCOPE-3', 'SCOPE-15'],
    steps: ['Read the dashboard with HQ active, then with Erode active'],
    expected: ['Totals differ and each matches that branch’s own rows'],
  },
  {
    id: 'ML-301', area: 'Branch Isolation', priority: 'P0', automation: 'auto',
    title: 'Loans list never mixes branches',
    rules: ['SCOPE-3'],
    steps: ['Compare the loans list under HQ and Erode with the database'],
    expected: ['Each list equals exactly that branch’s loan set'],
  },
  {
    id: 'ML-302', area: 'Branch Isolation', priority: 'P0', automation: 'auto',
    title: 'A loan detail page from another branch is not reachable',
    rules: ['SCOPE-3', 'API-5'],
    steps: ['With HQ active, open the detail route of an Erode loan'],
    expected: ['Not found — never a rendered page from the wrong branch'],
  },
  {
    id: 'ML-303', area: 'Branch Isolation', priority: 'P0', automation: 'auto',
    title: 'Approvals queue is branch-scoped',
    rules: ['SCOPE-12'],
    steps: ['Create pending items in both branches', 'Open approvals under each'],
    expected: ['Each branch sees only its own pending work'],
  },
  {
    id: 'ML-304', area: 'Branch Isolation', priority: 'P0', automation: 'auto',
    title: 'Superadmin gets no branch-scope exemption',
    rules: ['SCOPE-15'],
    steps: ['As superadmin with Erode selected, read customers, loans and wallet'],
    expected: ['All are limited to Erode', 'Selecting All Branches is the only way to widen'],
  },
  {
    id: 'ML-305', area: 'Branch Isolation', priority: 'P0', automation: 'auto',
    title: 'Branch admin cannot reach another branch’s data',
    rules: ['SCOPE-3'],
    steps: ['As the HQ admin attempt to read Erode rows'],
    expected: ['Only HQ rows are ever returned'],
  },
  {
    id: 'ML-306', area: 'Branch Isolation', priority: 'P0', automation: 'auto',
    title: 'Every customer, loan and wallet row carries a branchId',
    rules: ['SCOPE-4', 'SCOPE-13'],
    steps: ['Scan the run’s customers, loans and wallet transactions'],
    expected: ['No branchId is null — an unbranched row is a defect, not a feature'],
  },
  {
    id: 'ML-307', area: 'Branch Isolation', priority: 'P0', automation: 'auto',
    title: 'Pickers and modals are branch-scoped too',
    rules: ['SCOPE-16'],
    steps: ['Open the loan customer picker under Erode'],
    expected: ['Only Erode customers are offered'],
  },
  {
    id: 'ML-308', area: 'Branch Isolation', priority: 'P0', automation: 'auto',
    title: 'Tenant isolation holds across the two registered tenants',
    rules: ['SCOPE-1'],
    steps: ['With tenant A credentials request tenant B rows by id'],
    expected: ['404 for every model — no cross-tenant read'],
  },
  {
    id: 'ML-309', area: 'Branch Isolation', priority: 'P1', automation: 'auto',
    title: 'Branch cash pools never aggregate each other',
    rules: ['SCOPE-14'],
    steps: ['Sum wallet movements per branch and compare with each pool balance'],
    expected: ['Each pool equals its own movements only'],
  },
  {
    id: 'ML-310', area: 'Branch Isolation', priority: 'P1', automation: 'auto',
    title: 'Agent list served to mobile is branch-scoped',
    rules: ['SCOPE-12'],
    steps: ['GET /api/v1/agents with an Erode branch context'],
    expected: ['Only Erode agents are returned'],
  },

  // ─────────────────────────── N. Accounting ───────────────────────────
  {
    id: 'ML-330', area: 'Accounting', priority: 'P0', automation: 'auto',
    title: 'Cash book records disbursals and collections',
    rules: ['ACC-6'],
    steps: ['Read AccountEntry rows after a disbursal and a collection'],
    expected: ['A cash-book row exists for each money event'],
  },
  {
    id: 'ML-331', area: 'Accounting', priority: 'P0', automation: 'auto',
    title: 'Journal entries balance',
    rules: ['ACC-3'],
    steps: ['Sum debits and credits per JournalEntry'],
    expected: ['Every entry balances'],
  },
  {
    id: 'ML-332', area: 'Accounting', priority: 'P0', automation: 'auto',
    title: 'Journal dedup keys prevent double posting',
    rules: ['DB-10', 'ACC-5'],
    steps: ['Read dedupKey, sourceType and sourceId on auto-posted entries'],
    expected: ['All three are set and dedupKey values are unique'],
  },
  {
    id: 'ML-333', area: 'Accounting', priority: 'P1', automation: 'auto',
    title: 'Statutory accounting is gated by the subscription',
    rules: ['ACC-4'],
    steps: ['With premium accounting off, originate a loan'],
    expected: ['The cash book is still written; GL posting is skipped rather than failing'],
  },
  {
    id: 'ML-334', area: 'Accounting', priority: 'P1', automation: 'auto',
    title: 'Accounting pages are branch-scoped and closed to agents',
    rules: ['SCOPE-3', 'ROLE-4'],
    steps: ['Open the accounting page per branch, then as an agent'],
    expected: ['Branch-limited figures; agent refused'],
  },

  // ─────────────────────────── O. GPS ───────────────────────────
  {
    id: 'ML-345', area: 'GPS & Agent Location', priority: 'P1', automation: 'auto',
    title: 'Route tracker is gated when the GPS add-on is off',
    rules: ['MOD-1'],
    steps: ['With gpsTrackingEnabled false open /microlending/route-tracker'],
    expected: ['A feature-disabled panel renders instead of the live map'],
  },
  {
    id: 'ML-346', area: 'GPS & Agent Location', priority: 'P1', automation: 'auto',
    title: 'Enabling the GPS add-on renders the live map page',
    steps: ['Set gpsTrackingEnabled true and reopen the page'],
    expected: ['The tracker renders with the agent list'],
  },
  {
    id: 'ML-347', area: 'GPS & Agent Location', priority: 'P1', automation: 'auto',
    title: 'Agent location ping is recorded',
    steps: ['POST a GPS ping as agent A1'],
    expected: ['A location row is stored with coordinates and a timestamp for A1'],
  },
  {
    id: 'ML-348', area: 'GPS & Agent Location', priority: 'P0', automation: 'auto',
    title: 'Live agent map is branch-scoped',
    rules: ['SCOPE-12'],
    steps: ['Read the live agent list with HQ active, then Erode'],
    expected: ['Only that branch’s agents appear'],
  },
  {
    id: 'ML-349', area: 'GPS & Agent Location', priority: 'P1', automation: 'auto',
    title: 'Collection captures the agent location and a verification status',
    steps: ['Submit a collection with coordinates'],
    expected: ['The entry stores coordinates and a verification status'],
  },
  {
    id: 'ML-350', area: 'GPS & Agent Location', priority: 'P2', automation: 'manual',
    title: 'GPS history purge job trims old pings',
    rules: ['CRON-2'],
    steps: ['Run /api/cron/gps-purge with the cron secret'],
    expected: ['Pings older than the retention window are deleted; the job is idempotent'],
  },
  {
    id: 'ML-351', area: 'GPS & Agent Location', priority: 'P2', automation: 'manual',
    title: 'Denied location permission is recorded, not silently dropped',
    steps: ['Submit a collection with the location permission denied'],
    expected: ['Verification status records location_denied'],
  },

  // ─────────────────────────── P. Dashboard & reports ───────────────────────────
  {
    id: 'ML-365', area: 'Dashboard & Reports', priority: 'P0', automation: 'auto',
    title: 'Dashboard renders for superadmin, admin and agent',
    steps: ['Open the module dashboard for each role'],
    expected: ['Each renders its own view without a server error or a blank page'],
  },
  {
    id: 'ML-366', area: 'Dashboard & Reports', priority: 'P0', automation: 'auto',
    title: 'Dashboard KPI figures match the underlying rows',
    steps: ['Compare the active loan count with the database for the active branch'],
    expected: ['The KPI equals the branch-scoped query result'],
  },
  {
    id: 'ML-367', area: 'Dashboard & Reports', priority: 'P1', automation: 'auto',
    title: 'Reports index lists the micro-lending reports',
    steps: ['Open /microlending/reports as admin'],
    expected: ['The report catalog renders with runnable reports'],
  },
  {
    id: 'ML-368', area: 'Dashboard & Reports', priority: 'P0', automation: 'auto',
    title: 'Agent performance report is branch-scoped',
    rules: ['SCOPE-12'],
    steps: ['Run the agent report under HQ and Erode'],
    expected: ['Each lists only that branch’s agents'],
  },
  {
    id: 'ML-369', area: 'Dashboard & Reports', priority: 'P2', automation: 'auto',
    title: 'A report export downloads',
    steps: ['Export a report'],
    expected: ['A file is produced with a non-zero size'],
  },
  {
    id: 'ML-370', area: 'Dashboard & Reports', priority: 'P1', automation: 'auto',
    title: 'Analytics is closed to agents',
    rules: ['ROLE-4'],
    steps: ['Request /microlending/analytics as A1'],
    expected: ['Refused server-side'],
  },

  // ─────────────────────────── Q. NPA ───────────────────────────
  {
    id: 'ML-385', area: 'NPA', priority: 'P1', automation: 'auto',
    title: 'Classification ladder follows the RBI day buckets',
    rules: ['NPA-1'],
    steps: ['Classify loans at 0, 15, 45, 75 and 120 days overdue'],
    expected: ['standard, sma_0, sma_1, sma_2 and an NPA sub-category respectively'],
  },
  {
    id: 'ML-386', area: 'NPA', priority: 'P1', automation: 'auto',
    title: 'npaClassifiedAt is stamped once and never restamped',
    rules: ['NPA-2', 'X-15'],
    steps: ['Run the classifier twice on an NPA loan'],
    expected: ['The original classification timestamp survives the second run'],
  },
  {
    id: 'ML-387', area: 'NPA', priority: 'P2', automation: 'auto',
    title: 'Provisioning percentages match the category table',
    rules: ['NPA-4'],
    steps: ['Compute provisioning per category, unsecured'],
    expected: ['0.40% standard and SMA, 15% sub-standard, 100% unsecured doubtful and loss'],
  },
  {
    id: 'ML-388', area: 'NPA', priority: 'P2', automation: 'auto',
    title: 'NpaHistory rows are immutable',
    rules: ['DB-2', 'X-15'],
    steps: ['Attempt to update or delete an NpaHistory row'],
    expected: ['IMMUTABLE_RECORD is thrown'],
  },
  {
    id: 'ML-389', area: 'NPA', priority: 'P2', automation: 'manual',
    title: 'NPA upgrade needs three clean instalments and an admin action',
    rules: ['NPA-7'],
    steps: ['Pay three consecutive instalments, then request the upgrade'],
    expected: ['Upgrade only succeeds on explicit admin action after eligibility'],
  },

  // ─────────────────────────── R. Security ───────────────────────────
  {
    id: 'ML-400', area: 'Security & Negative', priority: 'P0', automation: 'auto',
    title: 'Out-of-scope records return 404, never 403',
    rules: ['API-5', 'X-12'],
    steps: ['Request another tenant’s loan and customer by id'],
    expected: ['404 in every case'],
  },
  {
    id: 'ML-401', area: 'Security & Negative', priority: 'P0', automation: 'auto',
    title: 'Agent token is refused on admin-only endpoints',
    rules: ['REQ-1', 'AUTH-1'],
    steps: ['Call an approvals or settings write endpoint with an agent token'],
    expected: ['403 — the handler refuses independently of the proxy'],
  },
  {
    id: 'ML-402', area: 'Security & Negative', priority: 'P0', automation: 'auto',
    title: 'A forged x-zolofund-* header is ignored',
    rules: ['REQ-2', 'X-5'],
    steps: ['Send a request with a hand-set x-zolofund-active-branch for another branch'],
    expected: ['Scope is unchanged — a header from outside is never trusted'],
  },
  {
    id: 'ML-403', area: 'Security & Negative', priority: 'P1', automation: 'auto',
    title: 'Password hashes and tokens never appear in responses',
    rules: ['X-13'],
    steps: ['Read the user and customer API payloads'],
    expected: ['No passwordHash, token or secret in any field'],
  },
  {
    id: 'ML-404', area: 'Security & Negative', priority: 'P1', automation: 'auto',
    title: 'Script payloads in text fields are stored inertly',
    steps: ['Create a customer whose name contains a script tag'],
    expected: ['The value is escaped when rendered — no script executes'],
  },
  {
    id: 'ML-405', area: 'Security & Negative', priority: 'P2', automation: 'manual',
    title: 'File upload rejects disallowed types',
    steps: ['Upload an executable as a customer photo'],
    expected: ['Refused by type and size validation'],
  },
  {
    id: 'ML-406', area: 'Security & Negative', priority: 'P1', automation: 'auto',
    title: 'A suspended tenant is walled off but can still reach billing',
    steps: ['Suspend the tenant subscription and load a module page'],
    expected: ['The payment wall renders; the billing route stays reachable'],
  },
  {
    id: 'ML-407', area: 'Security & Negative', priority: 'P1', automation: 'auto',
    title: 'Agents cannot switch module via X-App-Type',
    rules: ['AUTH-3'],
    steps: ['Send X-App-Type for another module with an agent token'],
    expected: ['The agent stays pinned to their JWT appType'],
  },

  // ─────────────────────────── S. Notifications ───────────────────────────
  {
    id: 'ML-430', area: 'Notifications & Approvals', priority: 'P0', automation: 'auto',
    title: 'Every approval request pairs with an approver notification',
    rules: ['X-23'],
    steps: ['Create pending customers and loans', 'Compare ApprovalRequest rows with notifications'],
    expected: ['No approval request exists without a notification to approvers'],
  },
  {
    id: 'ML-431', area: 'Notifications & Approvals', priority: 'P1', automation: 'auto',
    title: 'Notifications page lists staff notifications',
    steps: ['Open /microlending/notifications as admin'],
    expected: ['The approval notifications are listed'],
  },
  {
    id: 'ML-432', area: 'Notifications & Approvals', priority: 'P1', automation: 'auto',
    title: 'An approval decision notifies the requester',
    steps: ['Approve a loan raised by A1', 'Read A1 notifications'],
    expected: ['A decision notification exists for the agent'],
  },
  {
    id: 'ML-433', area: 'Notifications & Approvals', priority: 'P2', automation: 'manual',
    title: 'Notifications dispatch after commit, never inside the money transaction',
    rules: ['X-19'],
    steps: ['Review the origination and collection paths'],
    expected: ['notify() calls sit after the transaction boundary'],
  },

  // ─────────────────────────── T. Borrower portal ───────────────────────────
  {
    id: 'ML-445', area: 'Borrower Portal', priority: 'P1', automation: 'auto',
    title: 'Borrower login page renders',
    steps: ['Open /borrower/login'],
    expected: ['The borrower login form renders'],
  },
  {
    id: 'ML-446', area: 'Borrower Portal', priority: 'P1', automation: 'auto',
    title: 'Borrower sees only their own loan',
    rules: ['SCOPE-1'],
    steps: ['Log in as the borrower and open the dashboard'],
    expected: ['Their loan is shown; no other customer’s loan is reachable'],
  },
  {
    id: 'ML-447', area: 'Borrower Portal', priority: 'P2', automation: 'auto',
    title: 'Borrower self-pay posts against their own loan, locked and attributed',
    rules: ['MONEY-11'],
    pre: 'Micro-lending self-pay posts directly — the payment-intent queue is a chits-module control, not this one',
    steps: ['Submit a self-payment from the borrower portal'],
    expected: [
      'A collection entry is written against the borrower’s own loan',
      'It is marked as self-pay and locked against edits',
      'A cash self-payment waits on staff verification; a UPI one is verified',
    ],
  },
];

export const CASE_INDEX = new Map(CASES.map((c) => [c.id, c]));
